sudo: required
dist: trusty

language: c

services:
  - docker

before_install:
  - docker pull nickg/libinjection-docker

script:
  - docker run -v $HOME:/workspace -w /workspace nickg/libinjection-docker ls -l

